### ISSUE TITLE
#[derive(MessageResponse)]

### ISSUE THREAD

**Issue by rotty** [actix/actix-derive#13]
I think it would make sense to add a `MessageResponse` custom derive, along the lines of the [`SIMPLE_RESULT` macro](https://github.com/actix/actix/blob/bbb81901eb47e17a42e70c4357216c60f55e858d/src/handler.rs#L288). I know there's the `MessageResult` helper, but I prefer not having to wrap my result types.

I've read through the issues #1 and #2, and understand the reluctance to add new macros if they only save a small amount of code, but in this case (as shown by the existence of `SIMPLE_RESULT` ;-)), I think the boilerplate saved is enough to justify a custom derive.

**Comment by JohnTitor** [comment]
I think we can close this issue by #14.
