### ISSUE TITLE
Way of specifying none in derive message

### ISSUE THREAD

**Issue by kingoflolz** [actix/actix-derive#4]
Hi,

Is there a way of using this lib to derive a message which has an empty Item as well as an empty Error?

The way I'm currently doing it is
```rust
type none = ();

#[derive(Message)]
#[Message(none, none)]
struct Wake;
```

Thanks in advance

**Comment by fafhrd91** [comment]
I think, by default `#[derive(Message)]` should use unit for item and error

**Comment by kingoflolz** [comment]
Just tried it, seems like it unwraps on this line with no Message attr:
https://github.com/actix/actix-derive/blob/master/src/message.rs#L8

I can create a PR for that behavior if you think it is a good idea.
