### ISSUE TITLE
Give publish permission to ActixDeriveAdmins

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-derive#6]
@callym i need you to give publish permission ActixDeriveAdmins for actix_derive crate and add me to owners. my email is fafhrd91@gmail.com

**Comment by callym** [comment]
I've hopefully added you as an owner, it won't let me add `actixderiveadmins`, as `only members of a team can add it as an owner`, but you should be able to add it now you're an owner I think

**Comment by fafhrd91** [comment]
I still don't see myself as an owner of the package

**Comment by callym** [comment]
Have you gotten an invite on crates.io? I've tried adding you again and I don't get an error

**Comment by fafhrd91** [comment]
I didn’t get any invitation

**Comment by fafhrd91** [comment]
you are part of ActixDeriveAdmins team now, you should be able to give owner role to this group

**Comment by callym** [comment]
I've just given the group owner role (hopefully!)

**Comment by fafhrd91** [comment]
thanks! everything works
